apiVersion: v1
kind: Service
metadata:
  name: python-test-service
spec:
  selector:
    app: python-test-imdb
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-test-imdb
spec:
  selector:
    matchLabels:
      app: python-test-imdb
  replicas: 3
  template:
    metadata:
      labels:
        app: python-test-imdb
    spec:
      containers:
      - name: python-test-imdb
        image: 20732078/python_imdb
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        
